import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export const dynamic = "force-dynamic"

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <main className="min-h-screen bg-background flex flex-col text-white">
          <div className='bg-gray-600 w-full max-w-xl h-screen mx-auto'>{children}</div>
        </main>
      </body>
    </html>
  )
}
